### ISSUE TITLE
Is there an easy explanation of the epddl format?

### ISSUE THREAD

**Issue by aindilis** [sysulic/MEPK#1]
Hi,
   I've read through your paper but did not fully understand it.  I was wondering if there was a tutorial or faq or such for epddl?  Thanks,

Andrew

**Comment by fangbq** [comment]
@aindilis Oh, sorry! I haven't noticed your message! Right now, we only have this paper that explained the implementation of the code. But we plan to document this well soon. Thank you, appreciate your concern.

**Comment by aindilis** [comment]
Great, thank you for your reply.  I look forward to it.

**Comment by fangbq** [comment]
The detailed description of epddl is included in our journal paper now. Check the link https://www.sciencedirect.com/science/article/pii/S0004370221001132
